aplication/aplication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from odontologico.views import dashboard

urlpatterns = [
    path(r'dashboard/', dashboard, name='dashboards'),
    path('admin/', admin.site.urls),
    path(r'', include('odontologico.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplication/odontologico/forms.py
from datetime import datetime
import os
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.forms import DateTimeInput, ModelChoiceField

from odontologico.models import Genero, Modulo, Paciente, Doctor, Horario_hora, Tratamiento


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()
            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")

def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True


def campo_requerido(form, campo):
    form.fields[campo].widget.attrs['required'] = True


def campo_no_requerido(form, campo):
    form.fields[campo].widget.attrs['required'] = False


def habilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = False
    form.fields[campo].widget.attrs['disabled'] = False


def campo_solo_lectura(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True


class RegistroUsuarioForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(RegistroUsuarioForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            self.fields['password1'].widget.attrs['class'] = "form-control"
            self.fields['password2'].widget.attrs['class'] = "form-control"

    email = forms.EmailField(label="Email", widget=forms.TextInput(attrs={'class': 'form-control', }))
    nombre1 = forms.CharField(label="1er. Nombre", widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)', }))
    nombre2 = forms.CharField(label="2do. Nombre", widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)', }))
    apellido1 = forms.CharField(label="Apellido paterno", widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)', }))
    apellido2 = forms.CharField(label="Apellido materno", widget=forms.TextInput(attrs={'class': 'form-control', 'onKeyPress' : 'return solo_letras(event)',}))
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_numeros(event)',}))
    genero = forms.ModelChoiceField(label=u"Género", queryset=Genero.objects.filter(status=True),
                                    widget=forms.Select(attrs={'class': 'form-control', }))
    telefono_movil = forms.CharField(label=u"Teléfono móvil", max_length=50, help_text="Ingrese su número de telefono sin el 0",
                                     widget=forms.TextInput(attrs={'class': 'form-control', }))
    telefono_convencional = forms.CharField(label=u"Teléfono Convencional", max_length=50, required=False,
                                            widget=forms.TextInput(attrs={'class': 'form-control', }))


    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Nombre de usuario ya existe.")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email ya existe")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("La contraseña no coincide.")

        return password2

    class Meta:
        model = User
        fields = ("username", "email",)

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',

                }
            ),
        }

class ModuloForm(forms.Form):
    nombre = forms.CharField(label='Nombre', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)', }))
    descripcion = forms.CharField(label='Descripción', required=True,
                                  widget=forms.TextInput(attrs={'class': ' form-control ','onKeyPress' : 'return solo_letras(event)', }))
    ruta = forms.CharField(label='Ruta', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    icono = forms.ImageField(label='Icono', required=False, widget=forms.ClearableFileInput(
        attrs={'class': 'dropify', 'data-allowed-file-extensions': 'PNG png'}))
    activo = forms.BooleanField(label='Activo', required=False, widget=forms.CheckboxInput(
        attrs={'class': 'form-check form-switch ms-2 my-auto is-filled'}))

    def add(self):
        campo_requerido(self, 'icono')

    def editar(self):
        campo_no_requerido(self, 'icono')


class PersonaForm(forms.Form):
    nombres = forms.CharField(label='Nombres', required=True,
                             widget=forms.TextInput(attrs={'class': ' form-control','onKeyPress' : 'return solo_letras(event)',  }))
    # nombre2 = forms.CharField(label='2ª Nombre', required=True,
    #                          widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)',  }))
    apellidos = forms.CharField(label='Apellidos', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)', }))
    # apellido2 = forms.CharField(label='2º Apellido', required=True,
    #                          widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_letras(event)',  }))
    email = forms.CharField(label="Correo electrónico", max_length=200, required=False,
                            widget=forms.TextInput(attrs={'class': 'form-control',}))
    cedula = forms.CharField(label="Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'class': 'form-control','onKeyPress' : 'return solo_numeros(event)',}))
    genero = forms.ModelChoiceField(label="Género",required=True, queryset=Genero.objects.filter(status=True),
                                  widget=forms.Select(attrs={'class': 'form-control',}))

    telefono_movil = forms.CharField(label="Teléfono móvil", max_length=50, required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'(99 123 1234)'}))
    telefono_convencional = forms.CharField(label=u"Teléfono fijo", max_length=50, required=False,
                                    widget=forms.TextInput(attrs={'class': 'form-control ',}))
    ciudad = forms.CharField(label=u"Ciudad", max_length=50, required=False,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': '(Naranjito)'}))
    direccion = forms.CharField(label=u"Dirección", required=False,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': '(Dirección)'}))
    referencia = forms.CharField(label=u"Referencia", max_length=50, required=False,
                                     widget=forms.TextInput(
                                         attrs={'class': 'form-control', 'placeholder': '(Referencia)'}))


    def editar(self):
        campo_solo_lectura(self, 'cedula')
        campo_solo_lectura(self, 'genero')

class DoctorForm(forms.Form):
    nombre1 = forms.CharField(label='1ª Nombre', required=True,
                             widget=forms.TextInput(attrs={'class': ' form-control', }))
    nombre2 = forms.CharField(label='2ª Nombre', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control', }))
    apellido1 = forms.CharField(label='1ª Apellido', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control', }))
    apellido2 = forms.CharField(label='2º Apellido', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control', }))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.TextInput(attrs={'class': 'form-control',}))
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control',}))
    genero = forms.ModelChoiceField(label=u"Gènero",required=True, queryset=Genero.objects.filter(status=True),
                                  widget=forms.Select(attrs={'class': 'form-control',}))

aplication/templates/asistente/add_asistente.html
{% extends 'formularioBase.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido_extra %}

{% endblock %}
{% block lista_de_items_many_to_many %}
{% endblock %}
{% block titulo %}{{ titulo_formulario }}{% endblock %}
{% block class_extra_card_formulario %}col-lg-8 col-md-10{% endblock %}
{% block inputs_extras %}
    <input type="hidden" name="peticion" value="{{ peticion }}">
{% endblock %}

{% block news_inputs_form %}

{% endblock %}
{% block nombre_boton_submit %}Guardar{% endblock %}
{% block location_href_destino %}{% url 'asistentes' %}{% endblock %}
{% block botones_extras %}{% endblock %}

{% block modals %}
    <!-- Modal -->

{% endblock %}




{% block js %}

   <script>

       var mask = IMask(document.getElementById('id_telefono_movil'), {mask: '00 000 0000'});
       var mask = IMask(document.getElementById('id_telefono_convencional'), {mask: '000 000 0000'});
   </script>

    <script>
        var opciones = {
            strict: true,              // va a validar siempre, aunque la cantidad de caracteres no sea 10 ni 13
            events: "change",          // evento que va a disparar la validación
            the_classes: "invalid",    // clase que se va a agregar al nodo en el que se realiza la validación
            onValid: function () {

                if ($("#id_cedula").val().length == 10) {
                    $.ajax({
                        type: "GET",
                        url: {{request.path}},
                        dataType: "json",
                        data: {
                            'peticion': 'validar_cedula',
                            'cedula': $("#id_cedula").val(),
                        },
                        success: function (data) {
                            if (data.respuesta === true) {
                                mensajeDanger(data.mensaje)
                            }
                        },
                        error: function () {
                            alert("Error de conexión.");
                        },

                    });
                }

            },   // callback cuando la cédula es correcta.
            onInvalid: function () {
                if ($("#id_cedula").val().length == 10) {
                    mensajeWarning("cédula es incorrecta.");

                }

            }  // callback cuando la cédula es incorrecta.
        };

        $("#id_cedula").validarCedulaEC(opciones);

    </script>

    <script>

        function mensajeSuccess(mensaje) {
            Swal.fire('', mensaje, 'success')
        }

        function mensajeWarning(mensaje) {
            Swal.fire('', mensaje, 'warning')
        }

        function mensajeDanger(mensaje) {
            Swal.fire('', mensaje, 'error')
        }

        $(function () {

            $('#id_email').on('blur', function () {
                email = $("#id_email").val()
                if (email.length > 0) {


                    $.ajax({
                        type: "GET",
                        url: {{request.path}},
                        dataType: "json",
                        data: {
                            'peticion': 'validar_email',
                            'email': email,
                        },
                        success: function (data) {
                            if (data.respuesta === true) {
                                mensajeDanger(data.mensaje)
                            } else {

                            }
                        },
                        error: function () {
                            alert("Error de conexión.");
                        },

                    });
                }
            });
        });
    </script>


{% endblock %}

aplication/templates/asistente/edit_asistente.html
{% extends 'formularioBase.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block titulo %}{{ titulo_formulario }}{% endblock %}
{% block class_extra_card_formulario %}col-lg-8 col-md-10{% endblock %}
{% block inputs_extras %}
    <input type="hidden" name="peticion" value="{{ peticion }}">
    <input type="hidden" name="id" value="{{ asistente.id }}">
{% endblock %}
{% block news_inputs_form %}

{% endblock %}
{% block nombre_boton_submit %}Modificar{% endblock %}
{% block location_href_destino %}{% url 'asistentes'%}{% endblock %}
{% block botones_extras %}{% endblock %}



{% block js %}


      <script>

        var mask = IMask(document.getElementById('id_telefono_movil'), { mask: '00 000 0000'});
        var mask = IMask(document.getElementById('id_telefono_convencional'), { mask: '000 000 0000'});
    </script>

{% endblock %}

aplication/templates/asistente/view.html
{% extends 'baseapp.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido %}

    <div class="col-md-12 mb-lg-0 mb-4 ">
        <div class="position-relative  card mt-1 ">
            <div class="card-header pb-0 p-3 ">
                <div class="row ">
                    <div class="col-6 d-flex align-items-center">
                        <h6 class="mb-0">{{ titulo_tabla }}</h6>
                    </div>
                    <div class="col-6 text-end">
                        <a class="btn btn-outline-dark btn-sm mb-0" href="?peticion=add_asistente"><i
                                class="material-icons text-sm">add</i>&nbsp;&nbsp;Agregar</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-3">
                <div class="row">

                       <div class="table-responsive-lg">
                            <table class="table table-striped table-hover align-items-center mb-0 ">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolde text-center">N°.
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Nombres / Cédula
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Usuario
                                </th>
                                <th class=" text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Email
                                </th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Acciones
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for fila in page_obj %}
                                <tr>
                                    <td class="text-uppercase text-secondary text-xxs font-weight-bolder text-center">{{ forloop.counter }}</td>
                                    <td data-title="Nombre/ Cedula">
                                         <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">{{ fila.persona }}</h6>
                                                <p class="text-xs text-secondary mb-0"><strong>Cédula:{{ fila.persona.cedula }} </strong> </p>
                                            </div>
                                    </td>
                                    <td data-title=" Ruta(url)">
                                        <span class="text-xs">{{ fila.persona.usuario }}</span>

                                    </td>
                                    <td class="text-xs" data-title="¿Activo?">
                                         <span class="text-xs">{{ fila.persona.email }}</span>

                                    </td>
                                    <td class="text-secondary text-sm font-weight-bolder text-center">
                                        <div class="dropstart">
                                            <a href="javascript:;" class="text-secondary" id="dropdownMarketingCard" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="material-icons text-xl">more_vert</i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-lg-start px-2 py-3" aria-labelledby="dropdownMarketingCard" style="">
                                                <li><a class="dropdown-item border-radius-md"  href="?peticion=edit_asistente&id={{ fila.pk }}">Editar</a></li>
                                                <li>
                                                    <hr class="dropdown-divider">
                                                </li>
                                                <li><a class="dropdown-item border-radius-md text-danger" href="javascript:;" onclick="eliminar_registro('eliminar_asistente','{{ fila }}','{{ fila.pk }}')" >Eliminar</a></li>
                                            </ul>
                                        </div>
                                    </td>


                                </tr>
                            {% empty %}
                                 <tr>
                                <td colspan="10" class="text-uppercase text-secondary text-xxs font-weight-bolde text-center" >No existen registro </td>
                            </tr>

                            {% endfor %}


                            </tbody>
                        </table>
                       </div>

                </div>
            </div>
            {% include 'paginador.html' %}
        </div>


    </div>




{% endblock %}

{% block script %}
    <script>


    </script>

{% endblock %}