aplication/aplication/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from odontologico.views import dashboard

urlpatterns = [
    path(r'dashboard/', dashboard, name='dashboards'),
    path('admin/', admin.site.urls),
    path(r'', include('odontologico.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplication/odontologico/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.db.models import Sum

from odontologico.funciones import ModeloBase

ESTADO_CITA = (
    (1, u"ATENDIDO"),
    (2, u"PENDIENTE"),
    (3, u"ANULADO"),
)

TIPO_ODONTOGRAMA = (
    (1, u"PRINCIPAL"),
    (2, u"HISTORICO"),
)

NECESITA_ATENCION = (
    (1, u"SI"),
    (2, u"NO"),
)

class Modulo(ModeloBase):
    nombre = models.CharField(verbose_name="Nombre del módulo", max_length=100, unique=True)
    descripcion = models.CharField(verbose_name="Descripción", default='', max_length=200)
    icono = models.ImageField(verbose_name="Icono", upload_to='icono/')
    ruta = models.CharField(default='', max_length=200, unique=True, verbose_name='Ruta')
    activo = models.BooleanField(verbose_name="¿Módulo activo?")

    class Meta:
        verbose_name = "Módulo del sistema"
        verbose_name_plural = "Módulos del sistema"
        ordering = ['id']
        unique_together = ('ruta',)

    def __str__(self):
        return u'%s' % self.nombre

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.strip().capitalize()
        self.descripcion = self.descripcion.strip().capitalize()
        return super(Modulo, self).save(*args, **kwargs)


class Genero(ModeloBase):
    nombre = models.CharField(max_length=100, verbose_name=u'Género')

    class Meta:
        verbose_name = "Género"
        verbose_name_plural = "Géneros"
        ordering = ['id']

    def __str__(self):
        return u'%s' % self.nombre


class Persona(ModeloBase):
    usuario = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=100, verbose_name=u'1er Nombre')
    # nombre2 = models.CharField(max_length=100, verbose_name=u'2do Nombre')
    apellidos = models.CharField(max_length=100, verbose_name=u"1er Apellido")
    # apellido2 = models.CharField(max_length=100, verbose_name=u"2do Apellido")
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo electronico personal")
    cedula = models.CharField( max_length=10, verbose_name=u'Cédula', null=True, blank=True)
    telefono_movil = models.CharField(max_length=10, verbose_name=u"Teléfono móvil", null=True, blank=True)
    telefono_convencional = models.CharField(max_length=10, verbose_name=u"Teléfono convencional", null=True, blank=True)
    genero = models.ForeignKey(Genero, null=True, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=300, verbose_name=u'Direccion', null=True, blank=True)
    referencia = models.CharField(max_length=400, verbose_name=u'Referencia', null=True, blank=True)
    ciudad = models.CharField(max_length=400, verbose_name=u'Referencia', null=True, blank=True)

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"
        ordering = ['id']

    def __str__(self):
        return u'%s %s' % (self.apellidos, self.nombres)


    def tiene_perfil_persona(self):
        return self.personaperfil_set().exists()

class PersonaPerfil(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    is_paciente = models.BooleanField(default=False, verbose_name=u'Es paciente')
    is_administrador = models.BooleanField(default=False, verbose_name=u'Es administrador')
    is_especialista = models.BooleanField(default=False, verbose_name=u'Es especialista')
    is_asistente = models.BooleanField(default=False, verbose_name=u'Es asistente')

    class Meta:
        verbose_name = "Perfil de persona"
        verbose_name_plural = "Perfiles de personas"
        ordering = ['id']

    def __str__(self):
        if self.es_paciente():
            return u'%s' % "PACIENTE"
        elif self.es_administrador():
            return u'%s' % "ADMINISTRADOR"
        elif self.es_especialista():
            return u'%s' % "ESPECIALISTA"
        elif self.es_asistente():
            return u'%s' % "ASISTENTE"
        else:
            return u'%s' % "NO TIENE PERFIL"

    def es_paciente(self):
        return self.es_paciente

    def es_administrador(self):
        return self.es_administrador

    def es_especialista(self):
        return self.es_especialista

    def es_asistente(self):
        return self.es_asistente

class Paciente(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    necesita_atencion = models.IntegerField(choices=NECESITA_ATENCION, default=2, verbose_name=u'Necesita atencion')

    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"
        ordering = ['id']

    def __str__(self):
        return u'%s' % self.persona

    def tiene_odontograma(self):
        return self.agendarcita_set.filter(status=True, estado_cita=1).exists()

    def en_uso(self):
        existe = self.agendarcita_set.exists() | self.consulta_set.exists()
        return existe

    def totalrubros(self):
        total = Rubro.objects.filter(paciente_id=self.id, status=True).aggregate(total=Sum('valor'))
        if not total['total']:
            return 0.00
        return total['total']

    def totalpagos(self):
        lista_rubros = Rubro.objects.filter(paciente_id=self.id, status=True).values_list('id')
        total = Pago.objects.filter(rubro_id__in=lista_rubros, status=True).aggregate(total=Sum('valorfinal'))
        valorpago = 0.00
        if total['total']:
            valorpago = total['total']
        return ("{0:.0f}".format(valorpago))

    def verificar_estadocuenta(self):
        lista_rubros = Rubro.objects.filter(paciente_id=self.id, cancelado=False, status=True)
        tienevalorapagar = False
        if lista_rubros:
            tienevalorapagar = True
        return tienevalorapagar




class Doctor(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    especialidad = models.CharField(max_length=400, verbose_name=u'Especialidad')

    class Meta:
        verbose_name = "Doctor"
        verbose_name_plural = "Doctores"
        ordering = ['id']

    def __str__(self):
        return u'%s' % self.persona

    def en_uso(self):
        existe = self.agendarcita_set.exists() | self.consulta_set.exists()
        return existe

class Asistente(ModeloBase):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Asistente"
        verbose_name_plural = "Asistentes"
        ordering = ['id']

    def __str__(self):
        return u'%s' % self.persona


class AccesoModulo(ModeloBase):
    grupo = models.ForeignKey(Group,  on_delete=models.CASCADE)
    modulo = models.ForeignKey(Modulo, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Acceso a módulo"
        verbose_name_plural = "Acceso a módulos"
        ordering = ['id']

    def __str__(self):
        return u'%s - %s - %s' % (self.grupo,self.modulo, self.activo)

class Horario_hora(ModeloBase):
    hora_inicio = models.TimeField(verbose_name=u"Hora inicio")
    hora_fin = models.TimeField(verbose_name=u"Hora fin")
    activo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Horario Horas de atención"
        verbose_name_plural = "Horarios Horas de atenciones"
        ordering = ['id']

    def __str__(self):
        return u'%s - %s' % (self.hora_inicio, self.hora_fin)

class AgendarCita(ModeloBase):
    paciente = models.ForeignKey(Paciente,  on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor,  on_delete=models.CASCADE)
    fecha = models.DateField(verbose_name=u'Fecha')
    horario = models.ForeignKey(Horario_hora,  on_delete=models.CASCADE)
    estado_cita = models.IntegerField(choices=ESTADO_CITA, null=True, blank=True, verbose_name=u'Estado cita')
    descripcion = models.CharField(max_length=400, verbose_name=u'Descripcion', default=u'')

    class Meta:
        verbose_name = "Agendar cita"
        verbose_name_plural = "Agendar citas"
        ordering = ['id']

    def __str__(self):
        return u'Paciente: %s - Especialista: %s - Fecha: %s - Horario: %s' % (self.paciente,self.doctor, self.fecha,self.horario)

class Odontograma(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, blank=True, null=True)
    tipo = models.IntegerField(choices=TIPO_ODONTOGRAMA, null=True, blank=True, verbose_name=u'Tipo')
    status = models.BooleanField(verbose_name="Estado del registro", default=True)
    TP18=models.CharField(max_length=50, null=True)
    BP18=models.CharField(max_length=50, null=True)
    RP18=models.CharField(max_length=50, null=True)
    LP18=models.CharField(max_length=50, null=True)
    CP18=models.CharField(max_length=50, null=True)
    CP17=models.CharField(max_length=50, null=True)
    TP17=models.CharField(max_length=50, null=True)
    BP17=models.CharField(max_length=50, null=True)
    RP17=models.CharField(max_length=50, null=True)
    LP17=models.CharField(max_length=50, null=True)
    CP16=models.CharField(max_length=50, null=True)
    TP16=models.CharField(max_length=50, null=True)
    BP16=models.CharField(max_length=50, null=True)
    RP16=models.CharField(max_length=50, null=True)
    LP16=models.CharField(max_length=50, null=True)
    CP15=models.CharField(max_length=50, null=True)
    TP15=models.CharField(max_length=50, null=True)
    BP15=models.CharField(max_length=50, null=True)
    RP15=models.CharField(max_length=50, null=True)
    LP15=models.CharField(max_length=50, null=True)
    CP14=models.CharField(max_length=50, null=True)
    TP14=models.CharField(max_length=50, null=True)
    BP14=models.CharField(max_length=50, null=True)
    RP14=models.CharField(max_length=50, null=True)
    LP14=models.CharField(max_length=50, null=True)
    CP13=models.CharField(max_length=50, null=True)
    TP13=models.CharField(max_length=50, null=True)
    BP13=models.CharField(max_length=50, null=True)
    RP13=models.CharField(max_length=50, null=True)

aplication/templates/agendar_cita/add_cita.html
{% extends 'formularioBase.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido_extra %}

{% endblock %}
{% block lista_de_items_many_to_many %}
{% endblock %}
{% block titulo %}{{ titulo_formulario }}{% endblock %}
{% block class_extra_card_formulario %}col-lg-8 col-md-10{% endblock %}
{% block inputs_extras %}
    <input type="hidden" name="peticion" value="{{ peticion }}">
{% endblock %}

{% block news_inputs_form %}

{% endblock %}
{% block nombre_boton_submit %}Guardar{% endblock %}
{% block location_href_destino %}{% url 'agendar_cita' %}{% endblock %}
{% block botones_extras %}{% endblock %}

{% block modals %}
    <!-- Modal -->

{% endblock %}




{% block js %}

   <script>

    </script>

{% endblock %}

aplication/templates/agendar_cita/add_cita_online.html
{% extends 'formularioBase.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido_extra %}

{% endblock %}
{% block lista_de_items_many_to_many %}
{% endblock %}
{% block titulo %}{{ titulo_formulario }}{% endblock %}
{% block class_extra_card_formulario %}col-lg-8 col-md-10{% endblock %}
{% block inputs_extras %}
    <input type="hidden" name="peticion" value="{{ peticion }}">
{% endblock %}

{% block news_inputs_form %}

{% endblock %}
{% block nombre_boton_submit %}Guardar{% endblock %}
{% block location_href_destino %}{% url 'agendar_cita_online' %}{% endblock %}
{% block botones_extras %}{% endblock %}

{% block modals %}
    <!-- Modal -->

{% endblock %}




{% block js %}

   <script>

    </script>

{% endblock %}

aplication/templates/agendar_cita/view.html
{% extends 'baseapp.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido %}

    <div class="col-md-12 mb-lg-0 mb-4 ">
        <div class="position-relative  card mt-1 ">
            <div class="card-header pb-0 p-3 ">
                <div class="row ">
                    <div class="col-6 d-flex align-items-center">
                        <h6 class="mb-0">{{ titulo_tabla }}</h6>
                    </div>
                    <div class="col-6 text-end">
                        <a class="btn btn-outline-dark btn-sm mb-0" href="?peticion=add_cita"><i
                                class="material-icons text-sm">add</i>&nbsp;&nbsp;Agregar</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-3">
                <div class="row">

                       <div class="table-responsive-lg">
                            <table class="table table-striped table-hover align-items-center mb-0 ">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolde text-center">N°.
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Paciente | Nombres - Cédula
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Cita | Fecha - Hora - Especialista
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Descripción
                                </th>

                                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Estado
                                </th>

                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Acciones
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for fila in page_obj %}
                                <tr>
                                    <td class="text-uppercase text-secondary text-xxs font-weight-bolder text-center">{{ forloop.counter }}</td>
                                    <td data-title="Nombre/ Cedula">
                                         <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">{{ fila.paciente| upper }}</h6>
                                                <p class="text-xs text-secondary mb-0"><strong>CI: {{ fila.paciente.persona.cedula }} </strong> </p>
                                                  <p class="text-xs text-secondary mb-0"><strong> <i
                                                    class="fa fa-mobile-phone" title="MÓVIL"></i>
                                                +593 {{ fila.paciente.persona.telefono_movil }} </strong> <a
                                                    href='https://web.whatsapp.com/send?l=en&phone=+593{{ fila.paciente.persona.telefono_movil }}&text=Buen dia, se le recuerda que tiene una cita pendiente con el dentista, Fecha: {{ fila.fecha }} Hora: {{ fila.horario.hora_inicio }}     '
                                                    target="_blank" title="Enviar recordatorio" data-bs-toggle="tooltip" data-bs-placement="bottom" >
                                                <i class="fa fa-whatsapp"></i>
                                            </a></p>
                                            </div>
                                    </td>

                                    <td class="text-xs" data-title="¿Activo?">
                                        <h6 class="mb-0 text-xs">FECHA: {{ fila.fecha }}</h6>
                                        <h6 class="mb-0 text-xs">HORA: {{ fila.horario }}</h6>
                                        <p class="text-xs text-secondary mb-0">
                                            <strong>ESPECIALISTA: {{ fila.doctor| upper}} </strong></p>

                                    </td>

                                    <td class="text-xs" data-title="¿Activo?">
                                        <h6 class="mb-0 text-xs">{{ fila.descripcion }} </h6>
                                    </td>

                                     <td class="text-xs" data-title="¿Estado Cita?">

                                         {% if fila.estado_cita == 1 %}
                                             <span class="badge badge-sm bg-gradient-success">{{ fila.get_estado_cita_display }}</span>
                                         {% endif %}
                                         {% if fila.estado_cita == 2 %}
                                            <span class="badge badge-sm bg-gradient-warning">{{ fila.get_estado_cita_display }}</span>
                                         {% endif %}
                                         {% if fila.estado_cita == 3 %}
                                            <span class="badge badge-sm bg-gradient-danger">{{ fila.get_estado_cita_display }}</span>
                                         {% endif %}


                                    </td>
                                    <td class="text-secondary text-sm font-weight-bolder text-center">
                                        <div class="dropstart">
                                            <a href="javascript:;" class="text-secondary" id="dropdownMarketingCard" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="material-icons text-xl">more_vert</i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-lg-start px-2 py-3"
                                                aria-labelledby="dropdownMarketingCard" style="">
                                                {% if fila.estado_cita == 2 %}{#   pendiente #}

                                                    <li><a class="dropdown-item border-radius-md"
                                                           href="?peticion=edit_cita&id={{ fila.pk }}">Editar</a>
                                                    </li>

                                                    <li><a class="dropdown-item border-radius-md" onclick="enviar_recordatorio('enviar_correo','{{ fila.pk }}','{{ fila | upper }}')"
                                                           href="javascript:;">Enviar correo de
                                                        recordatorio</a>
                                                    </li>

                                                {% endif %}

                                                <li>
                                                    <hr class="dropdown-divider">
                                                </li>
                                                {% if fila.estado_cita == 2 or fila.estado_cita == 3 %}
                                                  <li><a class="dropdown-item border-radius-md text-danger"
                                                           href="javascript:;"
                                                           onclick="eliminar_registro('eliminar_cita','{{ fila }}','{{ fila.pk }}')">Eliminar</a>
                                                    </li>
                                                {% endif %}
                                                {% if fila.estado_cita == 2 %}{#   pendiente #}


                                                    <li><a class="dropdown-item border-radius-md text-danger"
                                                           href="javascript:;"
                                                           onclick="accion_anular_cita('anular_cita','{{ fila | upper }}','{{ fila.pk }}')">Anular cita</a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </td>


                                </tr>
                            {% empty %}
                                 <tr>
                                <td colspan="10" class="text-uppercase text-secondary text-xxs font-weight-bolde text-center" >No existen registro </td>
                            </tr>

                            {% endfor %}


                            </tbody>
                        </table>
                       </div>

                </div>
            </div>
            {% include 'paginador.html' %}
        </div>


    </div>




{% endblock %}

{% block script %}
    <script>
    function enviar_recordatorio(peticion,id,registro){
         Swal.fire({
            title: '¿Estás seguro de enviar un recordatorio a esta cita?',
            text: registro,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si, enviar!',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'GET',
                    url: '{{ reques.path }}',
                    async: false,
                    data: {
                        peticion: peticion,
                        id: id,
                    },
                    dataType: "json",
                    beforeSend: function () {

                    }
                }).done(function (data) {
                    if (data.respuesta === true) {
                        Swal.fire(
                            'Recordatorio Enviado!',
                            data.mensaje,
                            'success'
                        ).then(function () {
                            location.reload();
                        });
                    } else {

                        Swal.fire(data.mensaje);
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    mensaje_alerta('Error al intentar conectar con el servidor', 'Error de conexiòn');
                }).always(function () {
                });


            }

        })

    }

    function accion_anular_cita(peticion, registro, id) {

        Swal.fire({
            title: '¿Estás seguro de anular esta cita?',
            text: registro,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Si, Anular!',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: 'POST',
                    url: '{{ reques.path }}',
                    async: false,
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        peticion: peticion,
                        id: id,
                    },
                    dataType: "json",
                    beforeSend: function () {

                    }
                }).done(function (data) {
                    if (data.respuesta === true) {
                        Swal.fire(
                            'Eliminado!',
                            data.mensaje,
                            'success'
                        ).then(function () {
                            location.reload();
                        });
                    } else {

                        Swal.fire(data.mensaje);
                    }
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    mensaje_alerta('Error al intentar conectar con el servidor', 'Error de conexiòn');
                }).always(function () {
                });


            }

        })


    }

    </script>

{% endblock %}

aplication/templates/agendar_cita/view_cita_online.html
{% extends 'baseapp.html' %}
{% load static %}
{% block head %}

{% endblock %}
{% block contenido %}

    <div class="col-md-12 mb-lg-0 mb-4 ">
        <div class="position-relative  card mt-1 ">
            <div class="card-header pb-0 p-3 ">
                <div class="row ">
                    <div class="col-6 d-flex align-items-center">
                        <h6 class="mb-0">{{ titulo_tabla }}</h6>
                    </div>
                    <div class="col-6 text-end">
                        {% if not existe_cita_medica_pendiente %}
                            <a class="btn btn-outline-dark btn-sm mb-0" href="?peticion=add_cita"><i
                                    class="material-icons text-sm">add</i>&nbsp;&nbsp;Agregar</a>

                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="card-body p-3">
                <div class="row">

                    <div class="table-responsive-lg">
                        <table class="table table-striped table-hover align-items-center mb-0 ">
                            <thead>
                            <tr>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolde text-center">N°.
                                </th>
                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Paciente | Nombres - Cédula
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Cita | Fecha - Hora - Especialista
                                </th>

                                <th class="text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Estado
                                </th>

                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder">
                                    Acciones
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for fila in page_obj %}
                                <tr>
                                    <td class="text-uppercase text-secondary text-xxs font-weight-bolder text-center">{{ forloop.counter }}</td>
                                    <td data-title="Nombre/ Cedula">
                                        <div class="d-flex flex-column justify-content-center">
                                            <h6 class="mb-0 text-xs">{{ fila.paciente| upper }}</h6>
                                            <p class="text-xs text-secondary mb-0">
                                                <strong>CI: {{ fila.paciente.persona.cedula }} </strong></p>
                                        </div>
                                    </td>

                                    <td class="text-xs" data-title="¿Activo?">
                                        <h6 class="mb-0 text-xs">FECHA: {{ fila.fecha }}</h6>
                                        <h6 class="mb-0 text-xs">HORA: {{ fila.horario }}</h6>
                                        <p class="text-xs text-secondary mb-0">
                                            <strong>ESPECIALISTA: {{ fila.doctor| upper }} </strong></p>

                                    </td>

                                    <td class="text-xs" data-title="¿Estado Cita?">

                                        {% if fila.estado_cita == 1 %}
                                            <span class="badge badge-sm bg-gradient-success">{{ fila.get_estado_cita_display }}</span>
                                        {% endif %}
                                        {% if fila.estado_cita == 2 %}
                                            <span class="badge badge-sm bg-gradient-warning">{{ fila.get_estado_cita_display }}</span>
                                        {% endif %}
                                        {% if fila.estado_cita == 3 %}
                                            <span class="badge badge-sm bg-gradient-danger">{{ fila.get_estado_cita_display }}</span>
                                        {% endif %}


                                    </td>

                                    <td class="text-secondary text-sm font-weight-bolder text-center">

                                    </td>


                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10"
                                        class="text-uppercase text-secondary text-xxs font-weight-bolde text-center">No
                                        existen registro
                                    </td>
                                </tr>

                            {% endfor %}


                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            {% include 'paginador.html' %}
        </div>


    </div>




{% endblock %}
{% block modals %}

     <!-- Modal -->
    <div class="modal fade" id="modalGeneric_historial">

        <div class="modal-dialog modal-dialog-centered  modal-lg modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-uppercase"></h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body_historial">

                </div>
                   <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

{% block script %}

    <script>
        function ventana_modal(peticion, pk, titulo) {
            $.ajax({
                type: "GET",
                url: `{{ request.path }}`,
                dataType: "json",
                data: {
                    'peticion': peticion,
                    'id': pk,
                },
                success: function (data) {
                    if (data.respuesta === true) {
                        $('.modal-body_historial').html(data.data);
                        $('#modalGeneric_historial .modal-title').html(titulo);
                        $("#modalGeneric_historial").modal({backdrop: 'static'}).modal('show');
                    } else {
                        alert(data.mensaje);
                    }
                },
                error: function () {
                    alert("Error de conexión.");
                },

            });
        }
    </script>

{% endblock %}}